# Generated by Django 5.0.6 on 2024-05-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpassword',
            name='application_name',
        ),
        migrations.RemoveField(
            model_name='userpassword',
            name='application_type',
        ),
        migrations.RemoveField(
            model_name='userpassword',
            name='game_developer',
        ),
        migrations.RemoveField(
            model_name='userpassword',
            name='game_name',
        ),
        migrations.RemoveField(
            model_name='userpassword',
            name='website_name',
        ),
        migrations.RemoveField(
            model_name='userpassword',
            name='website_url',
        ),
    ]
